eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 8763
spring:
  application:
    name: client
