eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka/
server:
  port: 8762

cas:
  #cas服务端的地址
  server-url-prefix: http://gcdc-sso-pc/cas
  #cas服务端的登录地址
  server-login-url: http://gcdc-sso-pc/cas/login
  #当前服务器的地址(客户端)
  client-host-url: http://localhost:8762/
  #Ticket校验器
  validation-type: CAS

spring:
  application:
    name: client
  datasource:
    username: 
    password: 
    url: jdbc:jtds:sqlserver
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    hikari:
      connection-test-query: select 1
